version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - revive

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-same-issues: 3
  max-issues-per-linter: 0
