run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - gofmt
    - goimports
    - revive


issues:
  exclude-use-default: false
  max-same-issues: 3
  max-issues-per-linter: 0
  max-issues: 0
