services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moraedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      retries: 1
      timeout: 3s

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      PORT: ":8080"
      HOST: "0.0.0.0"
      DSN: "postgres://postgres:postgres@db:5432/moraedb?sslmode=disable"
      DB_MAX_OPEN_CONNS: "30"
      DB_MAX_IDLE_CONNS: "30"
      DB_MAX_IDLE_TIME: "900s"
      SECRET_KEY: "123qwe"
      SECURE_TOKEN: "false"
      AUTH_TOKEN_NAME: "auth_token"

volumes:
  pgdata:
