services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moraedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      retries: 1
      timeout: 3s

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      PORT: ":8080"
      HOST: "0.0.0.0"
      DSN: "postgres://postgres:postgres@db:5432/moraedb?sslmode=disable"
      DB_MAX_OPEN_CONNS: "30"
      DB_MAX_IDLE_CONNS: "30"
      DB_MAX_IDLE_TIME: "900s"
      SECRET_KEY: "123qwe"
      SECURE_TOKEN: "false"
      AUTH_TOKEN_NAME: "auth_token"
      MONGO_DSN: "mongodb://root:example@mongo:27017"
      MONGO_DB: "moraedb"

volumes:
  mongo-data:
  pgdata:
